### ISSUE TITLE
Foundry v12.*

### ISSUE THREAD

**Issue by Freezor** [mhilbrunner/foundryvtt-dnd5e-lang-de#21]
Hi,

[foundryvtt-dnd5e-lang-de](https://github.com/mhilbrunner/foundryvtt-dnd5e-lang-de) still shows as incompatible to the newest foundry version. Any idea on where this is stuck or where one might help you @mhilbrunner?

**Comment by mhilbrunner** [comment]
Mainly because I haven't yet upgraded to v12 myself as I'm waiting on some modules, and found no time to install a separate v12 test version to test yet. One easy thing might be to test this in a v12 Foundry and world (make backups!) and see if anything breaks, it might just work. :) I don't expect much to break at least.

Thanks for reaching out!

**Comment by Freezor** [comment]
Yeah I'm careful myself as well and I hoped "someone" would've already tried it ;-)
Maybe I'll try it soon

**Comment by mhilbrunner** [comment]
@Freezor V12 (and D&D 5E 3.3.0) should work fine as of the new module version [3.3.0](https://github.com/mhilbrunner/foundryvtt-dnd5e-lang-de/releases/tag/3.3.0), thanks to the efforts by @Szerina92.

Let us know if you run into any issues :)
